# -*- coding: utf-8 -*-
"""NLP Sentiment Analysis Amazon Reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BR5D7rvhi_DUXraWRxtrqbtTXWzYSFg_
"""

import numpy
import pandas
import matplotlib.pyplot as plt

reviews_file = open('/content/Amazon reviews NLP.txt')

text = reviews_file.read()

from wordcloud import WordCloud

wordcloud = WordCloud().generate(text)
plt.figure(figsize=(14,14))
plt.imshow(wordcloud)

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

sid = SentimentIntensityAnalyzer()

scores  = sid.polarity_scores(text)
scores